export const bannanghaData = [
    {
        id: 20900,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/12/21/ban-nang-ha-pusilung-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ PUSILUNG - by NiceDesign (Cao Cấp)",
        productPrice: "4.690.000",
        productDiscount: "-25%",
        productColor: "border: 1px solid #2B2A2A; background: #2B2A2A;",
        productColor2: "border: 1px solid #C9C0BB; background: #C9C0BB;",
    },
    // có quà
    {
        id: 20901,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/14/khung-ban-nang-ha-pusilung-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Khung bàn nâng hạ PUSILUNG - By NiceDesign (Cao cấp)",
        productPrice: "4.490.000",
        productColor: "border: 1px solid #C9C0BB; background: #C9C0BB;",
        productColor2: "border: 1px solid #2B2A2A; background: #2B2A2A;",
    },
    // có quà
    {
        id: 20902,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/14/khung-ban-nang-ha-cao-cap-fansi-by-nicedesign-thinkpro-nicespace-m4w.png",
        productName: "Khung bàn nâng hạ cao cấp FANSI - By NiceDesign",
        productPrice: "6.990.000",
        productDiscount: "-22%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20903,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/9/ban-nang-ha-puluong-oval-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ PULUONG - Oval - By NiceDesign (Cao Cấp)",
        productPrice: "7.490.000",
        productDiscount: "-28%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20904,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/12/22/ban-nang-ha-puluong-square-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ PULUONG - Square - By NiceDesign (Cao Cấp)",
        productPrice: "7.490.000",
        productDiscount: "-23%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    // có quà
    {
        id: 20905,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/10/ban-nang-ha-cao-cap-langbiang-square-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ Cao Cấp LANGBIANG - Square - By NiceDesign (Cao Cấp)",
        productPrice: "9.990.000",
        productDiscount: "-27%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
        productGift: "Quà tặng 800.000"
    },
    // có quà
    {
        id: 20906,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/14/ban-nang-ha-cao-cap-langbiang-oval-by-nicedesgin-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ Cao Cấp LANGBIANG - Oval - By NiceDesgin (Cao Cấp)",
        productPrice: "9.990.000",
        productDiscount: "-31%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
        productGift: "Quà tặng 800.000"
    },
    {
        id: 20907,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/4/22/mat-ban-go-puluong-chong-am-cao-cap-by-nice-design-thinkpro-nicespace-QGg.png",
        productName: "Mặt bàn PULUONG - by NiceDesign (Cao Cấp)",
        productPrice: "2.990.000",
        productDiscount: "-23%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20908,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/14/khung-ban-nang-ha-cao-cap-langbiang-by-nicedesgin-thinkpro-nicespace.png",
        productName: "Khung bàn nâng hạ cao cấp LANGBIANG - By NiceDesgin",
        productPrice: "5.990.000",
        productDiscount: "-22%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },               
    {
        id: 20909,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/5/31/mat-ban-taxua-by-nicedesign-cao-cap-thinkpro.png",
        productName: "Mặt bàn Taxua - by NiceDesign (Cao Cấp)",
        productPrice: "2.990.000",
        productDiscount: "-23%",
        productColor: "border: 1px solid #FBCF9D; background: #FBCF9D;",
        productColor2: "border: 1px solid #83540E; background: #83540E;",
    },
    {
        id: 20910,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/6/2/mat-ban-fansi-by-nicedesign-cao-cap-thinkpro.png",
        productName: "Mặt bàn FANSI - by NiceDesign (Cao Cấp)",
        productPrice: "8.990.000",
        productColor: "border: 1px solid #421515; background: #421515;",
    },
    {
        id: 20911,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/9/ban-nang-ha-cao-cap-fansi-square-by-nicedesign-cao-cap-thinkpro.png",
        productName: "Bàn nâng hạ Cao Cấp FANSI - Square - By NiceDesign (Cao Cấp)",
        productPrice: "12.990.000",
        productDiscount: "-25%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20912,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/12/21/ban-nang-ha-taxua-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ TAXUA - By NiceDesign (Cao Cấp)",
        productPrice: "5.190.000",
        productDiscount: "-29%",
        productColor: "border: 1px solid #9C9C9C; background: #9C9C9C;",
        productColor2: "border: 1px solid #000000; background: #000000;",
        productColor3: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20913,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/9/mat-ban-pusilung-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Mặt bàn PUSILUNG- by NiceDesign (Cao Cấp)",
        productPrice: "1.990.000",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20914,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/1/30/mat-ban-epione-smartdesk-all-black.png",
        productName: "Mặt bàn Epione SmartDesk",
        productPrice: "1.100.000",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
    },
    {
        id: 20915,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/1/9/z4007328321083_3e2f8f21e125ef44b9b0504e0940f83d.jpg",
        productName: "Mặt bàn gỗ Cao Cấp NatureBridge LANGBIANG - By NiceDesign",
        productPrice: "5.990.000",
        productDiscount: "-14%",
        productColor: "border: 1px solid #AA6200; background: #AA6200;",
        productColor2: "border: 1px solid #110E0C; background: #110E0C;",
        productColor3: "border: 1px solid #421515; background: #421515;",
        productColor4: "border: 1px solid #DD9453; background: #DD9453;",
    },
    {
        id: 20916,
        productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/8/9/ban-nang-ha-cao-cap-fansi-oval-by-nicedesign-cao-cap-thinkpro-nicespace.png",
        productName: "Bàn nâng hạ Cao Cấp FANSI - Oval - By NiceDesign (Cao Cấp)",
        productPrice: "12.990.000",
        productDiscount: "-26%",
        productColor: "border: 1px solid #000000; background: #000000;",
        productColor2: "border: 1px solid #DADDE0; background: #FFFFFF;",
        productGift: "Quà tặng 800.000"
    },
]