<template>
    <BaseProductContainer :product-infor="productInfor"></BaseProductContainer>
</template>

<script>
import BaseProductContainer from '../base-product-container.vue';
export default {
    components: {
        BaseProductContainer
    },
    data() {
        return {
            productInfor: [
                // inspiron 14 5430
                {
                    id: 21000,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/backend/uploads/product/avatar/2021/10/9/ps5-standard-edition-thinkprojpg",
                    productName: "Máy chơi game Sony PlayStation 5 - PS5",
                    productPrice: "9.490.000",
                    productDiscount: "-51%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                    productColor2: "border: 1px solid #9F1D35; background: #9F1D35;",
                },
                // có quà
                {
                    id: 21001,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/12/7/kinh-thong-minh-ar-rokid-max-thinkpro-epiczone.jpg",
                    productName: "Kính Thông Minh AR Rokid Max",
                    productPrice: "9.990.000",
                    productDiscount: "-17%",
                    productColor: "border: 1px solid #205381; background: #205381;",
                },
                // có quà
                {
                    id: 21002,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/11/21/may-choi-game-sony-playstation-5-slim-ps5-thinkpro-epiczone-occ.jpg",
                    productName: "Máy chơi game Sony PlayStation 5 Slim - PS5 Slim",
                    productPrice: "12.390.000",
                    productDiscount: "-27%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21003,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/10/2/kinh-thuc-te-ao-meta-quest-3-thinkpro-epiczone.png",
                    productName: "Kính Thực Tế Ảo Meta Quest 3",
                    productPrice: "13.490.000",
                    productDiscount: "-21%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21004,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/9/6/may-choi-game-lenovo-legion-go-thinkpro-epiczone-dQz.jpg",
                    productName: "Máy Chơi Game Lenovo Legion Go",
                    productPrice: "19.390.000",
                    productDiscount: "-8%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                },
                // có quà
                {
                    id: 21005,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/6/17/xreal-air-adapter-thinkpro-epiczone-IwP.png",
                    productName: "Xreal Air Adapter",
                    productPrice: "2.050.000",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                // có quà
                {
                    id: 21006,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/11/30/kinh-3d-thong-minh-xreal-air-thinkpro-epiczone-KIV.jpg",
                    productName: "Kính 3D thông minh Xreal",
                    productPrice: "7.990.000",
                    productDiscount: "-38%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                },
                {
                    id: 21007,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/12/21/Ảnh màn hình 2022-12-21 lúc 16.02.29.png",
                    productName: "Kính thực tế ảo PlayStation VR2",
                    productPrice: "13.490.000",
                    productDiscount: "-25%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21008,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/9/16/xreal-beam-adapter-thinkpro-epiczone.png",
                    productName: "Xreal Beam Adapter",
                    productPrice: "3.990.000",
                    productDiscount: "-13%",
                    productColor: "border: 1px solid #BEBEBE; background: #BEBEBE;",
                },               
                {
                    id: 21009,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/3/31/oled_zelda08.png",
                    productName: "Hộp đựng Nintendo Switch - Legend of Zelda™: Tears of the Kingdom Edition",
                    productPrice: "990.000",
                    productColor: "border: 1px solid #000000; background: #000000;",
                },
                {
                    id: 21010,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/8/nintendo-switch-console-oled-model-w-2.jpeg",
                    productName: "Máy chơi game Nintendo Switch OLED",
                    productPrice: "7.390.000",
                    productDiscount: "-33%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                    productColor2: "border: 1px solid #FF0000; background: #FF0000;",
                    productColor3: "border: 1px solid #3B0A0A; background: #3B0A0A;",
                    productColor4: "border: 1px solid #E7E0A5; background: #E7E0A5;",

                },
                {
                    id: 21011,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2023/1/29/Ảnh màn hình 2023-01-29 lúc 13.09.33.png",
                    productName: "Tay cầm Dualsense Edge PS5",
                    productPrice: "4.990.000",
                    productDiscount: "-17%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21012,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/3/9/XboxS_01.jpg",
                    productName: "Máy chơi game Xbox S",
                    productPrice: "6.990.000",
                    productDiscount: "-33%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21013,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/5/may-choi-game-valve-steam-deck-01.png",
                    productName: "Máy chơi game Valve Steam Deck",
                    productPrice: "11.290.000",
                    productDiscount: "-13%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                },
                {
                    id: 21014,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/3/15/Oculus Quest 2_01.png",
                    productName: "Kính Thực Tế Ảo Oculus Quest 2",
                    productPrice: "7.990.000",
                    productDiscount: "-13%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21015,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/19/nintendo-switch-pro-controller-41-700x700.jpg",
                    productName: "Tay cầm Nintendo Switch Pro Controller",
                    productPrice: "1.390.000",
                    productDiscount: "-29%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                    productColor2: "border: 1px solid #302C2C; background: #302C2C;",
                },
                {
                    id: 21016,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/3/17/dualsense Charging-ps5-01.jpg",
                    productName: "Sạc Tay Cầm PS5 - DualSense Charging Station",
                    productPrice: "490.000",
                    productDiscount: "-69%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21017,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/25/Jumanji.jpg",
                    productName: "Jumanji: The Video Game - Game Nintendo Switch",
                    productPrice: "490.000",
                    productDiscount: "-45%",
                    productColor: "border: 1px solid #FF0000; background: #FF0000;",
                },
                {
                    id: 21018,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/24/kinh-thuc-te-ao-pico-4-128gb-11_600410_636344fcc7a995.02887199.png",
                    productName: "Kính thực tế ảo Pico 4 - 128GB",
                    productPrice: "8.790.000",
                    productDiscount: "-22%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21019,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/23/dragon-ball-z-kakarot-a-new-power-awakens-set-switch-1400x1400h.jpeg",
                    productName: "Dragon Ball Z: Kakarot + A New Power Awakens Set US - Game Nintendo Switch",
                    productPrice: "690.000",
                    productDiscount: "-48%",
                    productColor: "border: 1px solid #FF0000; background: #FF0000;",
                },
                {
                    id: 21020,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/23/nba-2k22-switch-1400x1400.jpeg",
                    productName: "NBA 2K22 US - Game Nintendo Switch",
                    productPrice: "490.000",
                    productDiscount: "-42%",
                    productColor: "border: 1px solid #FF0000; background: #FF0000;",
                },
                {
                    id: 21021,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/22/5vkqx-5s7oqgnj-w-3grmzf5dfxzbtib.jpg",
                    productName: "Mario + Rabbids Kingdom Battle - Game Nintendo Switch",
                    productPrice: "690.000",
                    productDiscount: "-54%",
                    productColor: "border: 1px solid #0000FF; background: #0000FF;",
                },
                {
                    id: 21022,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/22/dragon_ball_fighterz_cho_nintendo_switch_grande.jpg",
                    productName: "Dragon Ball FighterZ - Game Nintendo Switch",
                    productPrice: "690.000",
                    productDiscount: "-54%",
                    productColor: "border: 1px solid #FFFF00; background: #FFFF00;",
                },
                {
                    id: 21023,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/22/Shin-Megami-Tensei-V-thinkpro-02.png",
                    productName: "Shin Megami Tensei V - Game Nintendo Switch",
                    productPrice: "690.000",
                    productDiscount: "-54%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                },
                {
                    id: 21024,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/21/monster_hunter_rise_nintendo_switch_e31dc88f81d14d469995a767942837ff_grande.jpg",
                    productName: "Monster Hunter Rise - Game Nintendo Switch",
                    productPrice: "890.000",
                    productDiscount: "-40%",
                    productColor: "border: 1px solid #93CCEA; background: #93CCEA;",
                },
                {
                    id: 21025,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/21/3a2a011a9ca9379148129ad44c9f57af.jpg",
                    productName: "Splatoon 2 - Game Nintendo Switch",
                    productPrice: "890.000",
                    productDiscount: "-40%",
                    productColor: "border: 1px solid #FFB5C5; background: #FFB5C5;",
                },
                {
                    id: 21026,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/21/b3e1c304617b44901bdc0ff3c17004e8.jpg",
                    productName: "Ring Fit Adventure - Game Nintendo",
                    productPrice: "1.590.000",
                    productDiscount: "-27%",
                    productColor: "border: 1px solid #FF0000; background: #FF0000;",
                },
                {
                    id: 21027,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/22/71ldCNgOCCL.jpg",
                    productName: "Pokemon Violet - Game Nintendo Switch",
                    productPrice: "1.390.000",
                    productColor: "border: 1px solid #A020F0; background: #A020F0;",
                },
                {
                    id: 21028,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/22/81EyjDeArUL.jpg",
                    productName: "Pokemon Scarlet - Game Nintendo Switch",
                    productPrice: "1.390.000",
                    productColor: "border: 1px solid #9F1D35; background: #9F1D35;",
                },
                {
                    id: 21029,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/10/29/307437603_1103472866954527_7451113060627274321_n.jpeg",
                    productName: "Kính thực tế ảo Meta Quest Pro",
                    productPrice: "27.990.000",
                    productDiscount: "-38%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                },
                {
                    id: 21030,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/10/15/ps4-pro-cuh-7106b-b01-1-500x500 (1).jpeg",
                    productName: "Máy chơi game Playstation PS4 Pro",
                    productPrice: "4.990.000",
                    productDiscount: "-38%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                    productColor2: "border: 1px solid #E9E9E9; background: #E9E9E9;",
                    productColor3: "border: 1px solid #B2AFAF; background: #B2AFAF;",
                    productColor4: "border: 1px solid #FF0000; background: #FF0000;",
                },
                {
                    id: 21031,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/9/29/microsoft-xbox-serri-x-0.jpeg",
                    productName: "Máy chơi game Xbox Series X 1TB",
                    productPrice: "13.500.000",
                    productDiscount: "-31%",
                    productColor: "border: 1px solid #000000; background: #000000;",
                },
                {
                    id: 21032,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/11/7/z3573281125366_f1ecda4b10fed41709cdbfc7d9f64707_93e52bf25f354a51b63e9cbcacf50919.jpeg",
                    productName: "Sạc Tay Cầm PS5 - DualSense Charging Station",
                    productPrice: "1.190.000",
                    productDiscount: "-37%",
                    productColor: "border: 1px solid #00FF00; background: #00FF00;",
                    productColor2: "border: 1px solid #FF0000; background: #FF0000;",
                    productColor3: "border: 1px solid #DADDE0; background: #FFFFFF;",

                },
                {
                    id: 21033,
                    productImg: "https://images.thinkgroup.vn/unsafe/460x460/filters:quality(100)/https://media-api-beta.thinkpro.vn/media/core/products/2022/3/17/dualsense-ps5-01.jpg",
                    productName: "Tay cầm Playstation PS5 DualSense",
                    productPrice: "1.490.000",
                    productDiscount: "-21%",
                    productColor: "border: 1px solid #DADDE0; background: #FFFFFF;",
                    productColor2: "border: 1px solid #000000; background: #000000;",
                    productColor3: "border: 1px solid #CC1495; background: #CC1495;",

                },
            ],
        }
    }
}
</script>

